dist: focal
language: node_js
node_js:
  - "4.0"
  - 14
  - 17
install:
  - npm install
  - npm test
env:
  - CXX=g++-4.8
  - PYTHON=3.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    - deadsnakes # python
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
    - python3.6
