dist: focal
language: node_js
python: "3.6"
node_js:
  - 14
  - 17
install:
  - npm install
  - npm test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    - deadsnakes # python
    packages:
    - gcc
    - g++
    - clang
    - cmake
    - cmake-data
