language: node_js
node_js:
  - "4.0"
  - 14
  - 17
python:
  - "3.6"
before_install:
  - "pyenv global 3.6"
  - "pip install pip --upgrade"
install:
  - npm install
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - cmake-data
